### ISSUE TITLE
Major improvements for the future of the crate?

### ISSUE THREAD

**Issue by Enet4** [ErikPartridge/parsnip#1]
Good day! Last week I was looking for a Rust crate for evaluation metrics of this sort, and now I'm surprised to see one just emerged from a few days ago. Your initiative is much appreciated! :)

With that said, I hold a perspective (or a vision) of a Rust library for evaluation metrics that I believe would long-term benefit the community of data scientists using Rust, and might bring it to a mature position in the ecosystem. To name a few ideas:

- Support for both multi-class and multi-label evaluation feels essential (I have quite often worked with the latter these days). This requires working with multi-dimensional data.
- The functions could be made more generic, so that they accept more kinds of element types other than `u64`.
- Integration with existing multi-dimensional array implementations, such as [`ndarray`](https://crates.io/crates/ndarray) and [`nalgebra`](https://crates.io/crates/nalgebra).
- An assortment of improvements can be made to the current code in general, such as giving the API better conformance to the [Rust API guidelines](https://rust-lang-nursery.github.io/api-guidelines/).

Would you be open to major changes to the API around these lines in future versions? Some of these ideas might not be in line with your current perspective of the crate (at least according to what I read in the readme file). But if you're willing to take this path, I would be glad to slowly contribute with pull requests, issues, and other pieces of advice, with or without maintenance privileges.

**Comment by ErikPartridge** [comment]
Hello!

This is definitely still a WIP and your feedback is much appreciated! I definitely am open to substantial changes to the API—I'm only a couple months in to learning Rust so the feedback is very appreciated 👍 

I'll try to tackle your suggestions in order:

- Multi-class and multi-label are both definitely on the horizon—they are in the list of things I'd like to do, but I'm still figuring out how to prioritize them (as I put their inclusion at roughly the same priority as non-categorical data).
- I agree the functions definitely do need to be made more generic
- Down the road I'd like to add implementations for `ndarray` and `nalgebra` as features—alongside `arrayfire` for GPU support. I would like to make them features though to avoid having to draw them all in as dependencies
- I'll definitely work on some code improvements and go through the book more in depth. I'd love to make this amazing—but I clearly need to get stronger at Rust.

I'm definitely interested in the path, would love your help :)

**Comment by Enet4** [comment]
I'm so glad that we're in tune. Although I have little time to spare at the moment (currently finishing my PhD), I hope to provide some insights and changes from time to time. For the time being, I might send in some small (but beneficial) changes during this week.

> - I agree the functions definitely do need to be made more generic

By taking advantage of certain traits (I'm thinking `Eq` might be enough, but we can check the `num` crate for more), we should be able to support a wider range of class identifier types.

> - Down the road I'd like to add implementations for ndarray and nalgebra as features—alongside arrayfire for GPU support. I would like to make them features though to avoid having to draw them all in as dependencies.

That was indeed what I had in mind. I did the same thing in my crate `nifti`, which supports converting a NIfTI-1 volume to an ndarray as a Cargo feature.

> 
> I'll definitely work on some code improvements and go through the book more in depth. I'd love to make this amazing—but I clearly need to get stronger at Rust.

My experience in Rust might also become yet another asset in your learning process. You can make pull requests of your future contributions if you would like them reviewed before being pushed upstream.

**Comment by ErikPartridge** [comment]
Thank you so much!

Yes, this is all so very valuable. I've already branched an implementation for all `Unsigned`, though I've realized it might be easily changed to `Integer` for those using negative class numbers.

Best of luck with your PhD!
