### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by Enet4** [ErikPartridge/parsnip#7]
There are cases where a failed operation should still allow the program to harmoniously recover and handle at a higher level. I believe that the checks for prediction/label lengths we are currently making are one of such cases. Rather than panicking if the number of elements on both ends do not match, these functions should return a `Result` containing that information.

I will provide additional details on how to do this tomorrow or so, but in the mean time, you might wish to read the [relevant section from the book](https://doc.rust-lang.org/stable/book/2018-edition/ch09-00-error-handling.html) as well as the [C-GOOD-ERR](https://rust-lang-nursery.github.io/api-guidelines/interoperability.html#c-good-err) guideline.

-----------------------

Id' say we don't need a utility crate for the error type. A plain `Error` enum type implementing the necessary traits will bring us a long way.

**Comment by ErikPartridge** [comment]
This, I've actually done before 👍 I'll try to get a pull request in tonight :)
